source 'https://rubygems.org'

gem 'rake', '~> 13.0'
gem 'rake_terraform', '~> 1.3'
gem 'rake_docker', '~> 2.7'
gem 'rake_circle_ci', '~> 0.3'
gem 'rake_github', '~> 0.3'
gem 'rake_ssh', '~> 0.2'
gem 'git', '~> 1.6'
gem 'semantic', '~> 1.6'
