# frozen_string_literal: true

source 'https://rubygems.org'

gem 'aws-sdk'
gem 'docker-api'
gem 'dotenv'
gem 'git'
gem 'nokogiri'
gem 'octopoller'
gem 'os'
gem 'rake'
gem 'rake_docker'
gem 'rake_factory', '~> 0.33.0'
gem 'rake_git', '~> 0.2.0'
gem 'rake_git_crypt', '~> 0.4.0'
gem 'rake_github'
gem 'rake_gpg'
gem 'rake_slack'
gem 'rake_terraform'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-rake'
gem 'rubocop-rspec'
gem 'ruby_git_crypt', '~> 0.1.0'
gem 'semantic'
gem 'serverspec'
